systemLog:
   destination: file
   path: "C:\Program Files\MongoDB\Server\6.0\log\mongodb.log"
   logAppend: true
storage:
   journal:
      enabled: true
processManagement:
   fork: true
net:
   bindIp: 127.0.0.1
   port: 27017
setParameter:
   enableLocalhostAuthBypass: false

security:
  authorization: "enabled"
...